### ISSUE TITLE
Prepare for 24pullrequests

### ISSUE THREAD

**Issue by erikaheidi** [phansible/phansible#102]
As December is coming, we will have a new season of 24pullrequests (http://24pullrequests.com/). This is an excellent opportunity to get contributors helping with the project! But in order to create a welcoming environment and seize the opportunity, we need to do a little work on Issues triage. It would be nice to create easy, entry-level issues that people could participate.

Does anybody know if there's anywhere on the project settings where we can create custom Labels? That would be great for filtering the issues that are suitable for the 24pullrequests initiative. I'm pretty sure we could get a lot of contributions if we make this.

**Comment by naxhh** [comment]
Bye bye 24pull requests :)
