### ISSUE TITLE
[front-end] Fix left menu on smaller screens

### ISSUE THREAD

**Issue by erikaheidi** [phansible/phansible#104]
The left menu is breaking on smartphones - we know that people are not supposed to use Phansible from a smartphone or tablet, but some people follow a link via Twitter just to have a look at the project and this looks ugly.

Ideally, we should hide this menu if the website is being visualized in smaller screens.

@naxhh did some work previously but wasn't able to finish, you can find the branch in the previous issue #69 .

![2014-11-26](https://cloud.githubusercontent.com/assets/293241/5202621/cd927644-757f-11e4-9f74-4de4ff243542.png)

**Comment by renatomefidf** [comment]
Hello,

You can check at master and PR #204 to see if it's ok (I'm not a designer, really)
I updated the entire front-end framework, updated the main containers for the new syntax and used the media queries in order to hide the menu!
