### ISSUE TITLE
[front-end] Include our Twitter in the website

### ISSUE THREAD

**Issue by erikaheidi** [phansible/phansible#107]
Include our new twitter [@phansible](http://twitter.com/phansible) in the website, possibly using a widget to show the last tweets from the account.

**Comment by tcsoares84** [comment]
I send the PR with feature. Report me if have errors. ;)

**Comment by debo** [comment]
@tcsoares84 sorry for the late reply, I'm back, this is just to let you know that I'm going to review your PR soon. Thanks for your contribution.

**Comment by InFog** [comment]
Solved by https://github.com/phansible/phansible/pull/246
