### ISSUE TITLE
Hostname is not defined.

### ISSUE THREAD

**Issue by naxhh** [phansible/phansible#112]
I've an error when running a default generated playbook using Vagrant in windows.

The error is:
```
==> default: TASK: [init | Update /etc/hosts] **********************************************
==> default: fatal: [192.168.33.99] => One or more undefined variables: 'hostname' is undefined
```
You can check the full log: http://pastebin.com/xgSLExX3

Checking for #110 I've found this error.

Seems that this hostname is added in the Vagrant file.

Debugging the content returns:
```
==> default: ok: [192.168.33.99] => {
==> default:     "hostname": "{{ hostname }}"
==> default: }
```

**Comment by naxhh** [comment]
@Ajibola, @danizord 

Can any of you try this #171?

Should work. but I just want another confirmation :)

**Comment by Ajibola** [comment]
I actually used the ansible scripts generated on a linux server. Adding "hostname: Default" to the playbook.yml file solves this for me.

I reckon this should work across the board.

**Comment by crisu83** [comment]
For me the issue was that I didn't use the generated Vargantfile and I was missing the ```hostname``` variable in ```ansible.extra_vars```. Adding that fixed my issue.

**Comment by naxhh** [comment]
I think this was fixed. If not please let me know and I'll reopen
