### ISSUE TITLE
Coveralls.io isn't working anymore

### ISSUE THREAD

**Issue by sndpl** [phansible/phansible#147]
Since 23 november coveralls.io isn't updating anymore. This is probably because the github project url changed from Phansible/phansible to phansible/phansible.

Coveralls has an option to change the url in the UI (according to the docs), but the organisation isn't shown when logged in with my github account.

According to the commit logs I think only @InFog can fix it since he added the stats (correct me if i'm wrong :)).

**Comment by InFog** [comment]
I just checked everything and the only things that seems wrong is that I'm not one of the owners anymore :/

I'm not sure how to fix it. But, as I said, I don't like the "Only SomeoneVerySpecial can make it", so I'll investigate if it's possible to make it run with not need for me (or anyone) to be owner.

**Comment by fabiorphp** [comment]
Guys, I think we should no longer use the Coverals, but the Scrutinizer-CI.

What do you think of that?

**Comment by InFog** [comment]
Agree. Scrutinizer-CI has everything we currently need.

Created a new PR here #213.
