### ISSUE TITLE
HHVM Install error on ubuntu 14.04 trusty

### ISSUE THREAD

**Issue by Ajibola** [phansible/phansible#161]
There seems to be an error while trying to install hhvm on trusty due to a folder for trusty not being available on the ppa url. apt-get update throws an error just before the install hhvm command. 

W: Failed to fetch http://ppa.launchpad.net/mapnik/boost/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

**Comment by rogeriopradoj** [comment]
Same problem here.

https://gist.github.com/rogeriopradoj/2771da5e3484a3d2eb69

The main point of the error:

```
TASK: [hhvm | Add PPA repo] ***************************************************
failed: [192.168.33.99] => {"failed": true, "parsed": false}
SUDO-SUCCESS-njpuppiymekpqrekmkonddjuepyfdvda
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1420291149.87-142551595164248/apt_repository", line 2466, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1420291149.87-142551595164248/apt_repository", line 436, in main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 440, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: W:Failed to fetch http://ppa.launchpad.net/mapnik/boost/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found [IP: 91.189.95.83 80]
, E:Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by naxhh** [comment]
As @sndpl  said that change should work for you. I'm a bit bussy this holidays but I'll try to make this happend.
If someone wants to make the change please let me know :)

**Comment by naxhh** [comment]
this should be fixed
