### ISSUE TITLE
msg: No package matching 'php5-mbstring' is available

### ISSUE THREAD

**Issue by samplenull** [phansible/phansible#176]
Maybe it shoud be changed to libapache2-mod-php5 ? As suggested in http://serverfault.com/questions/455388/how-to-install-php-xml-and-php-mbstring-on-php-5-4-9-4

**Comment by naxhh** [comment]
Can you explain a bit more your set-up?

Did you choose to install php5-mbstring manually or was auto-added in some role?

**Comment by samplenull** [comment]
I've choosed manually to install "php5-mbstring" in PHP modules section.

**Comment by naxhh** [comment]
Please always provide all the info you can... can be no relevant for helps a lot...

What box are you using?

**Comment by samplenull** [comment]
Ubuntu 14.04 64, PHP 5.6, Nginx + PHP-FPM . I've choosed almost all default options, except for some extra PHP packages, including "php5-mbstring".

**Comment by naxhh** [comment]
The name of that package is really confusing... I guess will work with FPM...

I will try that.
Also I need to try if 13.10 uses mbstring >_<

**Comment by sndpl** [comment]
mbstring is also included in the php-fpm and php-cli packages, there is no separate mb-string php package for ubuntu 14.04. But don't know since which version this is, mind that other distro's still have the php-mbstring package (ex CentOS).

**Comment by naxhh** [comment]
@sndpl thanks for that will do my life a bit easier....

Anyway we are not suporting CentOS right now :D

**Comment by Aculeo** [comment]
I just ran into this issue. Ubuntu 14.04, NGINX + PHP5-FPM. Added `php5-mbstring` to the list of PHP modules in the web interface, needless to say that failed when running `vagrant up`.

But `php --info` shows that mbstring is there. So it indeed seems that it is already bundled into php5-fpm or some other package.

**Comment by naxhh** [comment]
This is related with: #67

If I remember correctly the package is bundled in some versions. So the problem is not really with phansible but that you don't really need to require it.
Or at least is how I understand the issue.

**Comment by panadol007** [comment]
Been searching for the answer for half day, then only realise cpanel / whm version of CentOS will disable yum to update php. You shall remove 'php*' from exclude list in /etc/yum.conf

**Comment by jsenin** [comment]
Yes, php5-mbstring package has been removed from ubuntu and debian repositories and now is a built-in feature https://packages.debian.org/es/squeeze-lts/php5-cli
