### ISSUE TITLE
Remove 13.10 box from master

### ISSUE THREAD

**Issue by naxhh** [phansible/phansible#178]
Hi!

13.10 is not an LTS version and now we have 14.04 so there is no point on maintaining 13.10 box on phansible.

I propose to remove it **from mater** (not from 1.0)

With this we remove one distro from our testing phase and make development of new roles and mainteinance faster and simpler.

Thoughts?

**Comment by InFog** [comment]
Yes, it should be removed.

**Comment by InFog** [comment]
I created the PR. If everything ok, merge please.

In case of any problems, we can discuss in #201.
