### ISSUE TITLE
Deploy 1.0

### ISSUE THREAD

**Issue by naxhh** [phansible/phansible#184]
@erikaheidi can you deploy 1.0 branch? we have a few bugs waiting for deployment (check wfd tag)

Thanks!

**Comment by erikaheidi** [comment]
yes definitely! doing it now

**Comment by erikaheidi** [comment]
done!

**Comment by InFog** [comment]
\o/

**Comment by InFog** [comment]
Since it's done, can we close this one?

**Comment by naxhh** [comment]
Thanks! yes. closing it :)
