### ISSUE TITLE
Install sql dump

### ISSUE THREAD

**Issue by Ekstazi** [phansible/phansible#187]
Please add support for installing sql dump in database/user/password section. Ansible option mysql_db already support it.

**Comment by Ekstazi** [comment]
I add this to my bundle by following that steps:
1. Modify `ansible/vars/mariadb.yml` by adding
```yml
dump:dump.sql
```
2. Modify `ansible/roles/mariadb/tasks/main.yml`:
```yml
- name: mariadb | Create databases
  mysql_db: name={{ mariadb.database }} state=import login_user=root login_password={{ mariadb.root_password }} target={{ mariadb.dump }}
```

**Comment by kinncj** [comment]
I volunteer to implement it for `MySQL`, `MariaDB` and `PostgreSQL`
