### ISSUE TITLE
Add support for vagrant-hostmanager plugin

### ISSUE THREAD

**Issue by Ekstazi** [phansible/phansible#188]
Please add support for vagrant-hostmanager plugin. I modify my local bundle by adding these line in my `Vagrantfile`:
```ruby
    if Vagrant.has_plugin?('vagrant-hostmanager')
        config.hostmanager.enabled           = true
        config.hostmanager.manage_host       = true
        config.hostmanager.ignore_private_ip = false
        config.hostmanager.include_offline   = false
        config.hostmanager.aliases           = ['pirpo.my','pirpo.dev']
    end

```

**Comment by Ekstazi** [comment]
This plugin modify your host file automatically so you can access your box by domain name(in this case "pirpo.my" and "pirpo.dev")

**Comment by naxhh** [comment]
As we said, we will go with pure ansible/vagrant configurations.
