### ISSUE TITLE
windows.sh script is included even if I untick the checkbox that asks to include it

### ISSUE THREAD

**Issue by baruica** [phansible/phansible#192]

**Comment by baruica** [comment]
Happened with Firefox and Chrome on Ubuntu 14.10 machine.

**Comment by InFog** [comment]
I confirm this.

But I guess the script is not run if the checkbox is disabled, right?

**Comment by baruica** [comment]
The text on the form does not imply that it should be executed, so it either has to be changed to be clearer, or the form handling has to be fixed.
I'll try and have a look this week.

**Comment by naxhh** [comment]
Pretty sure is not being executed because of this: https://github.com/phansible/phansible/blob/master/src/Phansible/Resources/ansible/templates/vagrant_local.twig#L52

Maybe we can use that same variable to prevent packing it.
If you think is worth it.

**Comment by InFog** [comment]
Hey, @baruica! Did you take a new look into this issue? Do you think it is still a issue? If not, we can close this one.

**Comment by renatomefidf** [comment]
It's not running, for me it's not an issue, the script is there, but it's a zombie!

**Comment by baruica** [comment]
I haven't had time to look at it, sorry.
The way I see it, either the label should say that it only installs the script instead of running it, or the scipt should be run if the checkbox is ticked.
I don't think it can just be left as is.

**Comment by naxhh** [comment]
As I see it. We have two options:
- We don't pack the windows.sh when the checkbox is off
- We pack it always but we remove the option to check/unchek.

Second option has nice side-effect that it will work if you don't have ansible in your host.
Bad side is the "magic" of why that worked

**Comment by InFog** [comment]
I vote for option 2. It is not increasing file's size significantly and some magic, sometimes, is not that bad.

**Comment by naxhh** [comment]
I found out some people does "not understand" this if thing...
I'm not sure if it's because they don't read the whole file or is something else...

we will go with opt 2 and try to make the explanation more explicit.

**Comment by InFog** [comment]
Good for me
