### ISSUE TITLE
Issue closing party/day

### ISSUE THREAD

**Issue by InFog** [phansible/phansible#193]
Hey, so, we have some pending issues and PRs.

What if we schedule a date and time to get together online to solve them?

CC @erikaheidi, @fabiorphp, @naxhh

**Comment by erikaheidi** [comment]
Sounds like fun :) like a hackaton thing. Let's call it Phansible Day :D I'm in

**Comment by InFog** [comment]
Yep, that's the idea. I guess with 3 or 4 people we can make it :)

**Comment by naxhh** [comment]
I will try to be there!

But will depend a lot on the day :\

But for now count with me!

Sorry for the late response :(

**Comment by InFog** [comment]
Nice, @naxhh.

Ok, let's start defining a time window. I guess 2 or 3 hours are enough, if we focus ;)

And then we can define a week day. I'm a morning person (ok, it sounds odd) and I'll try to push everyone into having it in the morning, maybe on a Saturday. The problem is that I don't know how many Americans (the whole America) will join us and the time differences may be an obstacle...

I guess, for now, we have only people on European timezones, but I believe we can have a lot more after a few words from @erikaheidi on twitter :D
