### ISSUE TITLE
Welcoming the new project lead: @naxhh

### ISSUE THREAD

**Issue by erikaheidi** [phansible/phansible#197]
Hello everybody! 

This is not an issue, it's an announcement, a good and important one :)

As you probably noticed it's being hard for me to keep up with the project development. So many things changed, and I am positive that those were good changes, but it's hard to keep track when you don't have time. I feel like I'm letting you guys down because by not knowing the source in detail anymore it's very hard for me to manage PRs and take care of deployments.

At the same time, I really want that Phansible keeps the original purpose of simplicity above all things. 

I've been talking with @naxhh about it because he is being very active in the project, much more than I am, and he also shares the same ideas I do, about simplicity. Very often, when I come to an issue he has already replied with exactly what I wanted to say :)

For that reason I invited him to assume officially a role as **lead developer** in Phansible, taking care of deploys and having a final word on PRs and issues. I will be participating as a contributor, and I also want to get back to the API project so we can do more with the project in the future.

I really believe this is a good change for the future of the project. 

Thank you Ignacio for accepting this role, I'm wishing you a pleasant journey :)

**Comment by mikeSimonson** [comment]
Long live to the new king :smile:

**Comment by InFog** [comment]
Good luck, @naxhh! And thanks for the good job so far, @erikaheidi :)

**Comment by naxhh** [comment]
Thanks for the good wishes :)

I'll try to make a big push this week/week-end
