### ISSUE TITLE
[UI] Menu not correctly displayed

### ISSUE THREAD

**Issue by naxhh** [phansible/phansible#203]
In current master:

![image](https://cloud.githubusercontent.com/assets/944635/7514093/9b7a65ee-f4ba-11e4-916c-ba5caabbfe15.png)

![image](https://cloud.githubusercontent.com/assets/944635/7514095/a011c1ba-f4ba-11e4-82a7-8e05f45c44eb.png)

![image](https://cloud.githubusercontent.com/assets/944635/7514097/a29b415e-f4ba-11e4-9698-1c49632f21b9.png)

**Comment by renatomefidf** [comment]
Here is how it looks to me:
![screenshot_2015-05-07-08-40-08](https://cloud.githubusercontent.com/assets/823634/7514640/af07dec2-f495-11e4-8050-a0d4893c949f.png)

Have you reloaded the page (disabling cache) after de merge?

**Comment by naxhh** [comment]
Is on the staging server and I tested it at home and at work :\

**Comment by renatomefidf** [comment]
Hello @naxhh, I just did a PR #204 

What's the staging URL so I can check it too!

**Comment by naxhh** [comment]
All looks ok!

We are not displaying the menu on desktops of 1024 but that's ok.

Thanks for the help!
