### ISSUE TITLE
Release Master branch

### ISSUE THREAD

**Issue by naxhh** [phansible/phansible#206]
So!
This weekend is THE weekend.

There are no more excuses. Sunday/monday I'll deploy master to production so all the testing should be done from today until sunday night (GMT+1).

Later in the day I'll upload the matrix for testing but if you check master it's really easy to know how to test it (In case you want to help)

we have webservers, php/hhvm, databases, system packages...
Finally we will test only in 13.10 and 14.04 so 12.04 can be ignored.

The way testing should go is creating the playbook for a configured VM and making vagrant up of that machine.

Then testing that all the things are installed as they should and that Webservers are really working.
So, if you install apache + php 5.6 test that apache is serving php files correctly.

Then come here and put the matrix you have tested. What commands you have issued to test things. `php --version` etc.. So we all know what has been tested and what not.

Report here problems and bugs!

Thanks a lot!

**Comment by naxhh** [comment]
0.6-rc tagged. https://github.com/phansible/phansible/tree/0.6-rc

This week will be the deploy.

**Comment by InFog** [comment]
Any news here?

**Comment by naxhh** [comment]
Yes! I'm a layer :(
You where able to test anything?
From where I was able to test I think the best approach is to just deploy it and see who complains of something not tested...

Do you agree? I can deploy it today.

**Comment by InFog** [comment]
Nice approach :) But you should watch the logs for some time after deployment.

**Comment by naxhh** [comment]
Deploy done. All seems ok. I'll be watching logs these days just in case.
