### ISSUE TITLE
Spurious "dist" variable in common.yml

### ISSUE THREAD

**Issue by tychay** [phansible/phansible#212]
My `ansible/vars/common.yml` has `dist: precise` (though I'm building on trusty). I don't see it used anywhere in my ansible playbook/roles so it's probably not needed. Suggest removing it since it's not being used and may be confusing. (Of course maybe it's used in some other buildout? If so, what's it for?)

**Comment by naxhh** [comment]
This should be related with: https://github.com/phansible/phansible/pull/172/files

But I think i just forgot to take it out.

Searching in the repo I don't find this var in any tpl

**Comment by InFog** [comment]
Are we already using the new version in production? Should be something related to older versions.

**Comment by naxhh** [comment]
Oh. that actually makes sense...
I'm closing this because this is related with the old version.

I'll deploy new version asap

**Comment by tychay** [comment]
Cool, thanks for looking into it. If I wasn't so lazy I'd do a composer install and work from there (but I am). :-)
