### ISSUE TITLE
Tell the user to correctly unzip phansible zip in MacOS

### ISSUE THREAD

**Issue by naxhh** [phansible/phansible#222]
Regarding #71

We should tell the user in a very explicit way that the inventory file should not be executable.
IN the MacOS case it also involves unziping the file correctly (not just double click but using unzip for example)

We need to decide where and how to display it..
What I can think of:
- A warning in phansible.com
- A step that checks for this somewhere in the provisioning and alerts of the issue and how to resolve it
- Your call.

**Comment by mbernson** [comment]
+1, I ran into this issue when I tried out Phansible today.

**Comment by naxhh** [comment]
This should be fixed in https://github.com/ansible/ansible/pull/11643

So a test will be nice :)

**Comment by jeroenseegers** [comment]
I can confirm I get a message when running `vagrant up` after using the OS X default Archive Utility telling me I should chmod the extracted file(s).

```
ERROR: The file ansible/inventories/dev is marked as executable, but failed to execute correctly. 
If this is not supposed to be an executable script, correct this with `chmod -x ansible/inventories/dev`.
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by naxhh** [comment]
Amazing! that's cool!

Now we can hope to not get more reports about this!

**Comment by HMAZonderland** [comment]
I tried to chmod the files. Destroyed the VM and reinstated by using vagrant up. Still did not work, still got the message. Restored the zip file from trash and extracted it with the command line unzip utility. That did work.

**Comment by naxhh** [comment]
@HMAZonderland ensure that you are using last version of ansible.

**Comment by HMAZonderland** [comment]
Installed from Brew.

**Comment by naxhh** [comment]
Please if you need assitance with this go to gitter and we can talk about it.
This was confirmed to be fixed by Ansible themselves (not by us) 

I'll block this issue.
