### ISSUE TITLE
PHP Version selection not retained

### ISSUE THREAD

**Issue by kozie** [phansible/phansible#232]
Even tho there is an option to choose between PHP version 5.6, 5.5 and 5.4, the generated file is always set to 5.6. I haven't quite tested the other options.

The `ansible/vars/all.yml` file has the php ppa version set to 5.6 so it seems the option isn't retained.

**Comment by naxhh** [comment]
I'll check assap. thanks

**Comment by kozie** [comment]
Added a [pull request](https://github.com/phansible/phansible/pull/233) (as it could be seen in the aforementioned event logs).

A wrong a jQuery selector has been used. The proposed change should fix the PHP PPA selection element. Tho the following could also be used `$('input[name=php\\[ppa\\]])` but i presume the usage of `$('#php_version')` is preferred to keep consistency.

Cheers!
