### ISSUE TITLE
Redundant mysql prefix

### ISSUE THREAD

**Issue by EmanueleMinotto** [phansible/phansible#241]
Inside *mysql/tasks/main.yml* every instruction has the prefix `mysql | `.
This is redundant because while provisioning every section is already used as prefix, so we'll see `mysql | mysql | ` instead of only one prefix like the other roles.

PS: I can submit a PR if the issue is confirmed

**Comment by naxhh** [comment]
Very true. If you want to provide that PR will be welcome :)

Regards.
