### ISSUE TITLE
ubuntu vivid boxes

### ISSUE THREAD

**Issue by designermonkey** [phansible/phansible#256]
Can we have the vivid boxes as part of the choice options please? I change them manually each time.

**Comment by fabiorphp** [comment]
You could create a PR for this! Please help us make a better software!

**Comment by designermonkey** [comment]
Wouldn't even know where to start. I use the website.

**Comment by naxhh** [comment]
We should totally add vivid boxes! Sadly I can't keep everything up to date with this and other projects but of course you can help here.

If I'm not wrong on this add vivid boxes should be as easy as adding them here

https://github.com/phansible/phansible/blob/35c08e9ec38e4187986201d96fd4aa13c0f44227/app/config/phansible/boxes.yml

**Comment by popstas** [comment]
Ubuntu Vivid is 15.04, not LTS and not latest. Maybe need to add 14.10, 15.04 and 15.10 and leave last LTS as default selected? In other words all versions since last LTS.

And, anybody needs 32-bit boxes?

**Comment by naxhh** [comment]
You are right. I didn't check if 15.04 was the latest one or not.
From my side the proposal sounds right.

**Comment by designermonkey** [comment]
I did this ages ago but stupidly PRd my own fork instead of this repo :(

**Comment by naxhh** [comment]
@designermonkey if you could add 15.10 that would be nice :)

**Comment by designermonkey** [comment]
Added a commit. I'm just going by the boxes available on vagrant cloud here. I know the 15.04 works fine as I use it.

**Comment by debo** [comment]
@designermonkey seen. It looks good to me.

@popstas I do think yes, some people, me included, still uses 32bit boxes by time to time.
