### ISSUE TITLE
Enable display_errors for php-fpm

### ISSUE THREAD

**Issue by nev3rm0re** [phansible/phansible#260]
In current configuration display_errors is set to off, so xdebug doesn't really do anything useful.

**Comment by naxhh** [comment]
Set it to on!

A bit old example here:
https://github.com/phansible/phansible/blob/35c08e9ec38e4187986201d96fd4aa13c0f44227/ansible/group_vars/devservers#L8

We try to set the values to "prod-mode" for safety

But if you want to contribute and enable it when xdebug is enabled. Go for it!
