### ISSUE TITLE
Suggestion: change the name of file ansible/inventories/dev

### ISSUE THREAD

**Issue by joserprieto** [phansible/phansible#267]
I see that in many of the examples of the web, in ansible, the inventory file is called:

ansible/inventories/hosts

I know that vagrant is made thinking in developments; but the change of the name can be confused for any users.

Regards.

**Comment by debo** [comment]
@joserprieto actually keep them separated by target environment is suggested as best practice

http://docs.ansible.com/ansible/playbooks_best_practices.html#staging-vs-production

A practice that I personally agree with. What do you think?
