### ISSUE TITLE
Newer version of nginx

### ISSUE THREAD

**Issue by ifdattic** [phansible/phansible#269]
I think it might be useful to update the nginx repository to install newer version of nginx (1.4.x => 1.8.x).

For example by adding by:

```
- name: Add Nginx Repository
  apt_repository: repo='ppa:nginx/stable' state=present
```

**Comment by debo** [comment]
@ifdattic I agree, would you mind do the honours creating a PR to the **phansible/role-nginx** repo

**Comment by ifdattic** [comment]
Will do a bit latter

**Comment by debo** [comment]
Thanks a lot for the contribution. Appreciated.

**Comment by ifdattic** [comment]
Available at https://github.com/phansible/role-nginx/pull/4

**Comment by debo** [comment]
@ifdattic thanks a lot, I added a little comment. As soon as it's fixed I'll merge it.

**Comment by debo** [comment]
https://github.com/phansible/role-nginx/pull/4 has just been merged. I'm going to close this and thanks @ifdattic once more for his contribution.
