### ISSUE TITLE
Feature request: .htaccess

### ISSUE THREAD

**Issue by kristoftorfs** [phansible/phansible#275]
Added a .htaccess file in the ansible directory with the contents `deny from all`.

**Comment by naxhh** [comment]
Hi. Can you explain better your request? Why do you want that?
I understand you want that here: https://github.com/phansible/phansible/tree/master/ansible

phansible.com runs under nginx, that's why I'm a bit confused.

**Comment by kristoftorfs** [comment]
Sorry, didn't think that one through as I wrote it down. I mean in the generated zip file. This way no passwords/server configuration can be access should it somehow end up on a production apache server.

**Comment by naxhh** [comment]
I don't really think you should upload your generated zip file to the server. Specially when ansible let's you provision it from your local pc.

@debo thoughts?

**Comment by debo** [comment]
Yes I think there is a bit of confusion here. @kristoftorfs ansible playbooks are never intended to be deployed to the server, it makes little sense. Also best practises are to use ansible vault for storing any sensitive information so to make more difficult to take advantage from leaks.

**Comment by kristoftorfs** [comment]
I know that, but accidents do happen, and the first thing I always do when creating a new box is adding this .htaccess file. More of a pre-emptive measure, but if it was automatically added that would save those two minutes each time :-)

**Comment by debo** [comment]
@kristoftorfs the thing is that it's not a bullet proof solution though, also, as @naxhh pointed out this won't work with nginx.

**Comment by kristoftorfs** [comment]
I know, but there is no bullet proof solution against stupidy :-) I just figured it could be usefull for anyone using Apache.

**Comment by debo** [comment]
If we make the change we need to target both platforms. Also, let's assume that the ansible folder will make its way to the production server, my question would be, why is it in a publicly accessible place? As you said, there is no bullet proof solution against stupidity so I'm tempted to let evolution make it's course :-P

**Comment by naxhh** [comment]
I'll reject this because I don't think it's really required. And also is platform dependent (apache).

Thanks for the idea and for taking the time to open the issue, but we will not go with this one.

**Comment by debo** [comment]
@kristoftorfs I have to agree with @naxhh I think that this goes somehow beyond Phansible purpose

**Comment by kristoftorfs** [comment]
@debo, @naxhh No problem, thanks for the discussion!

**Comment by debo** [comment]
@kristoftorfs we still welcome PRs though, if you do create one however, remember to support both platforms
