### ISSUE TITLE
Welcome Debo as the new Project Lead

### ISSUE THREAD

**Issue by naxhh** [phansible/phansible#276]
Because of lack of time to correctly test and deploy phansible in a constant way.
I'm moving away from Project Lead in phansible.

I've tried my best to keep phansible simple and to encourage people to try ansible and not just use phansible defaults. This is a great project with a great focus on teaching people how to do stuff and not just gave it done.

I trust Debo will do also his best to keep the main idea of the project and that he will be able to take care of better than I was able to.

So please. Welcome Debo as the new Phansible project lead.

**Comment by debo** [comment]
Thanks a lot @naxhh it's with lots of appreciation and excitement that I'm accepting the role. I'll try my best to keep the nature of the Phansible project true to its origin but up to date with what people nowadays need and look for.

_Phansible will live long and prosper!_

**Comment by HMAZonderland** [comment]
Congratulations. @naxhh please keep an eye out!

**Comment by debo** [comment]
Thanks @HMAZonderland and hell yeah, I hope @naxhh doesn't give up, Phansible still means community :)

**Comment by InFog** [comment]
Thanks for all the efforts @naxhh. You did a really good job.
@debo, thanks for taking over and good luck :)

**Comment by naxhh** [comment]
Closing this. Thanks for the kind words :)
