### ISSUE TITLE
Feature request: Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by e-moe** [phansible/phansible#280]
It would be really nice to have possibility to use Ubuntu 16.04 LTS

**Comment by debo** [comment]
@e-moe thanks for requesting this, I'll definitely look into it. It will need some proper testing but definitely doable.

**Comment by barrystaes** [comment]
As a new phansible user this was the first thing i wanted to try allong with PHP7 and MariaDB. Whats Ansible for if not for quickly trying new things? Ubuntu 16.04 is hardly new..

Bumping this issue up.

**Comment by debo** [comment]
@barrystaes I do understand and I do apologies for the time is taking me to promote all these updates but I am in the middle of an international relocation so I didn't have much time to focus on the project. I will do my best. Thanks for the understanding.

**Comment by vesper8** [comment]
3 months later.. any update on this? Is this project still alive? Been a while since an update. Wanted to give it a try but not being able to use the latest stack is a deal-breaker..

**Comment by debo** [comment]
@vesper8 yes it is but it's been a bit slowed down by me relocating to Australia and all the linked logistic pain and also my job keeping me busy but I am committed in bringing and moving everything forward this year.

**Comment by debo** [comment]
The [boxes are updated now](https://github.com/phansible/phansible/blob/b579ac5a3f349073a777db1f6fa0864a00c7957d/app/config/phansible/boxes.yml) as per request I am waiting for other issues to be solved before I can release the changes.

**Comment by vesper8** [comment]
thanks! and don't forget php 7.1 :)

very glad to hear you are returning to this project and planning to update it!!

**Comment by debo** [comment]
Don't worry, I won't forget
