### ISSUE TITLE
Issue with  ondrej/php5-5.6

### ISSUE THREAD

**Issue by PurpleHexagon** [phansible/phansible#289]
Was just about to start a new ansible playbook and used phansible for the base as I often do. 

There seems to be an issue with the following lines 

main.yml
```
apt_repository: repo=ppa:ondrej/{{ php.ppa }}
```

all.yml
```
php:
      ppa: php5-5.6
```

However I get the following error:

```
TASK [php : Add ppa Repository] ************************************************
fatal: [192.168.22.99]: FAILED! => {"changed": false, "failed": true, "msg": "failed to fetch PPA information, error was: HTTP Error 404: Not Found"}

```

This appears to be because of a change to the package:

https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages

As changing all.yml to the following works:
```
php:
      ppa: php
```

**Comment by debo** [comment]
@PurpleHexagon thanks for raising this, I will have a look at it as soon as my internet connection at home is sorted.

**Comment by Jacob87** [comment]
@PurpleHexagon It will install PHP if you set it to `ppa: php`, yes, but I think it defaults to PHP 7 rather than 5.6, if you do that. Can you confirm that?

**Comment by naxhh** [comment]
@Jacob87 it shouldn't since that's only the ppa.

And as @PurpleHexagon said the ppa is now named:
```
ppa:ondrej/php
```

Now we only need that ppa for php 5.4

Should review also the `php_version` since seems it has changed from php-7 to php7.0

**Comment by Jacob87** [comment]
@naxhh You are right, my mistake. However, I was just tweaking my phansible config and had to make sure to explicitly use the version number in all php packages i.e. `php5-common` to `php5.6-common`, when I changed to the `ppa:ondrej/php` repository.

**Comment by naxhh** [comment]
Yep. it seems part of the new repo structure.

**Comment by debo** [comment]
This is issue is now fixed as per https://github.com/phansible/role-php/pull/11 and will available in the next release.
