### ISSUE TITLE
I owe a big apologie

### ISSUE THREAD

**Issue by debo** [phansible/phansible#295]
Yes I owe a big apologie to the many people who believe in this project, the one who contributed to it, the one who submitted PRs and the one who are using it, I let you quite down for the past 3 months and I am very sorry, but I am still here, I didn't give up I simply was very busy between work and my relocation to Sydney.

I wanted to also let you know that the project is still alive and as of next month I will actively get back on track to move everything forward, the first step last month was to gain full control over the servers and domain because as you might know Erika decided to become a full time mum and even more now then ever needs my and the community support to keep the project she created moving forward.

I also want to thank you all for the patience and for not screaming at me despite being quite absent and silent all this time.

Thanks and sorry.

**Comment by debo** [comment]
As of March 2018 development of Phansible has restarted and it will continue to be so. Closing this issue for now.

**Comment by fnagel** [comment]
Is this project still active?

**Comment by debo** [comment]
@fnagel yes but also not now. As you can see [here](https://github.com/phansible/phansible/commits/master) I did restart working on the project this year, but all the COVID-19 madness kicked in and I had to reshuffle few things in life. Now things are a bit better so I will go back to revive the project, fixing the outstanding problems and modernising it.

**Comment by fnagel** [comment]
@debo Thanks for the quick answer! I'm currently searching for an alternative to PuPHPet in order to create new VMs vor local development. I'm not really a friend of docker (especially when I need to keep a few VirtualBox powered VMs for now) and Phansible looks really promising! I will keep an eye on your project :-)

**Comment by debo** [comment]
@fnagel no problem at all. I was under the impression puphpet was offering something similar to phansible in term of Vagrant support, the only difference is that we indeed use Ansible while they use Puppet. Moreover I'm not sure if it's just me or what but https://puphpet.com seems down at the moment.

I'll try to get back on track as soon as possible so that you and other people can start using it and help me out ironing any bug that might arise.
