### ISSUE TITLE
Close the Gitter channel

### ISSUE THREAD

**Issue by InFog** [phansible/phansible#299]
Do we still need that? Maybe we can keep the conversation on the issues and pull requests.

**Comment by debo** [comment]
@InFog I'm back to the living. The channel remained on hold for long time so I'm happy to close it. I will check if I have enough rights to do so, if not I will maybe need to get in touch with Erika for that.

**Comment by InFog** [comment]
Ok, thanks!

**Comment by debo** [comment]
After long overdue time this is now done. Unfortunately there was no middle ground other than destroy everything. If we see something like Gitter being useful again in future we can start anew.
