### ISSUE TITLE
Brace yourselves new architecture is coming

### ISSUE THREAD

**Issue by InFog** [phansible/phansible#31]
Hello, guys!

So, I spent last week think about this new architecture.

I know I put the views' files under "views/bundles". The thing is I'm still not happy with it, but I think it's better to have something that works than a beautiful thing just in my mind.

So I'll try to do the same with BundleController. I'm think of splitting the responsibilities for each part in separate files, just like the views, and this controller will just iterate over the available bundles looking for these files (classes) and sending the `$vagrant` object (maybe not just vagrant, we can change this too) to be kind of "decorated" by these classes.

Something like this:

```
$php = new PhpBundle();
$web = new WebserverBundle();
$sys = new SyspackagesBundle();

// Here I already have the $vagrant object
$vagrant;
$vagrant = $php->decorate($vagrant);
$vagrant = $web->decotare($vagrant);
$vagrant = $sys->decotare($vagrant);
```

Or, maybe something like this:

```
$php = new PhpBundle();
$web = new WebserverBundle();
$sys = new SyspackagesBundle();

// Here I already have the $vagrant object
$vagrant;
$vagrant->add($php);
$vagrant->add($web);
$vagrant->add($sys);
```

Of course I'm not going to instantiate the classes one by one, I'm going to use some kind of looping using the bundles defined in the configuration.

I think this way Phansible will be more easily extensible, since all we'll need to do is:

- Add the bundle name in config
- Add a view for the it
- Add a class that "decorates" the `$vagrant` object.

(I'm using the word "decorate" a lot in this text, but I'm not sure this is a real decorator, if you have a better name, just say it :smile: )

So, what do you guys think about it?

**Comment by InFog** [comment]
Yay, thanks for closing, @naxhh. I think we don't need this anymore. If I have any ideas, I open a new issue or PR :D

**Comment by naxhh** [comment]
Yes! thanks :)

I'm trying to clean the issue log a bit  :D
