### ISSUE TITLE
Error when attempting to run vagrant up for the first time 

### ISSUE THREAD

**Issue by thecrimpmaster** [phansible/phansible#71]
ERROR: The file ansible/inventories/dev is marked as executable, but failed to execute correctly. If this is not supposed to be an executable script, correct this with `chmod -x ansible/inventories/dev`.
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by naxhh** [comment]
I've checked and confirmed what @alimac says.

This is a problem related on how do you extract the zip, and not with the zip generation itself.

Use a tool like `unzip` and you wouldn't have this problem.

**Comment by holtkamp** [comment]
Maybe this, and https://github.com/haikulab/vagrant-statamic-lemp/issues/2 should be mentioned/checked somewhere when starting up the box. 

Starting with a tool like this and having to 'resolve' two issues before being able to continue does not really contribute to adoptability of this great solution..

**Comment by naxhh** [comment]
Hi @holtkamp regarding the current ticket, yes. we could add some kind of check for this. But this is not really a problem with phansible and could make our Vagrantfile harder to read... anyway I keep what you said in mind.

About the issue you link I don't really understand what you mean.
Phansible is a GUI for creating ansible playbooks. So, I think it's really obvious that you will need ansible installed.

Anyway if you have `Include windows.sh script to enable provisioning on Windows Hosts` option checked (it is by default) it will run ansible inside the box when you don't have ansible installed in your host machine...

**Comment by holtkamp** [comment]
@naxhh ,you are totally right. Running on Mac here, so the host machine is used, which did not have ansible installed.

Reason why I mentioned it, I encountered phansible.com through Twitter / a blog. Thought "lets give it a try" in those 30 spare minutes on a Friday afternoon. When such trivial issues occur, it is likely not to get a new try on Monday morning.

Some good old searching and puzzling until it just works makes it a challenge, but not everyone has time/patience for such puzzling / readying the complete Ansible documentation. That is why I posted my comment, just to improve usability and increase the chance that more people embrace this approach. Feel free to discard it though ;).

**Comment by naxhh** [comment]
Well we don't discard feedback just because.
I appreciate it a lot.

What is weird to me is that the windows.sh script should work in your mac too if you don't have ansible installed.
I'll need to check that.

Thanks again for the feedbakc.

**Comment by phillpafford** [comment]
having the same issue, running mac osx 10.8 using phansible.com (Which is awesome)

**Comment by GeeH** [comment]
Note - the fix is as follows for OSX:

> Do not just double click the zip file to unpack it from finder, instead use the command line `unzip` command to extract the files, then everything works fine.

**Comment by naxhh** [comment]
You are right @GeeH 

In fact I said that in the issue just after closing it.
I guess I'll need to do some alert somewhere to make it more explicit.

**Comment by GeeH** [comment]
hi @naxhh - I just wanted to add that at the bottom of the issue so people finding it via Google didn't have to read the whole thread :smiley:.

**Comment by GeeH** [comment]
Example:
```
unzip phansible_hhvm.zip -d <dir to extract to>
```

**Comment by trompx** [comment]
Just like here https://groups.google.com/forum/#!topic/ansible-project/rAM6mOEjwv4 with a windows host running ansible in a Virtualbox/Vagrant vm I get this error too...

**Comment by naxhh** [comment]
I'm loking this because things get harder to find. Any discussion on how we will make easier to the clients this proble should be discussed in #222 

Just in case I'll explain again the solution in MacOS:

`unzip phansible_hhvm.zip -d <dir to extract to>`
