### ISSUE TITLE
Use configuration files for generating the bundle

### ISSUE THREAD

**Issue by erikaheidi** [phansible/phansible#86]
This is something I've been thinking about for a long time. My idea is to create a configuration file in YAML that will be used to generate the bundle. The web interface will then be responsible for creating a compatible configuration file for generating the bundle.

This will enable:
* Easy creation of presets
* A CLI phansible.phar client a la Composer
* Decoupling the web interface from the real API
* Having an API!

Among other things that will be easier to implement with this.

What are your thoughts? :)

**Comment by naxhh** [comment]
Hi @erikaheidi 

Any update on this?
